### ISSUE TITLE
Some years passed by...and I got to this

### ISSUE THREAD

**Issue by arichiardi** [eggsyntax/code_challenge#1]
Hey @eggsyntax, I was preparing and I came across this old repository in my backup.

I said, hey, this looks like a very nice challenge for me to work on now. It indeed was!

So I went ahead and implemented the tree with zippers and now working on "way" to reduce the solution space.

First of all, thank you! It took me a while and I don't really remember why I did not do this before but it is a very well organized code challenge.

Secondly, I was thinking that the solution should be made a blog post because I don't think I have ever seen zippers (and content zippers) used this way before.

Therefore I wanted to ask if you are still using this for interviews and if not, if you allow me to work on a post.

No worries if not, I understand and will keep it secret!

Thanks again!

**Comment by eggsyntax** [comment]
Hey! Whoops, didn't see this until now. I'm not still at TI, let me check with them and see if they're still using it. Glad it was fun!

In retrospect I have to admit that I've never found an occasion to actually _use_ zippers in practice :laughing:

**Comment by arichiardi** [comment]
Thank you very much! Yeah I was thinking the same, please do let me know :smile:

**Comment by eggsyntax** [comment]
Hey! I heard back from them -- they do plan to use it again, but they feel OK about you writing a post if you can try to change identifying details enough that someone who applied wouldn't make the connection.

Thanks for asking, I appreciate it and I'm sure they do as well!

**Comment by arichiardi** [comment]
Cool thank you 😃
